version: '3'

services:
  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.2}
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  # -------------------------
  # Mimir - 3 Node Cluster
  # -------------------------
  mimir-1:
    image: grafana/mimir:${GRAFANA_MIMIR_VERSION:-2.13.0}
    hostname: mimir-1
    command:
      - -config.file=/etc/mimir/mimir.yaml
    volumes:
      - ./mimir.yaml:/etc/mimir/mimir.yaml:ro
      - mimir-data-1:/tmp/mimir-data
    ports:
      - "9009:9009" # expose only one node for Grafana
    networks:
      - mimir-net
    restart: unless-stopped

  mimir-2:
    image: grafana/mimir:${GRAFANA_MIMIR_VERSION:-2.13.0}
    hostname: mimir-2
    command:
      - -config.file=/etc/mimir/mimir.yaml
    volumes:
      - ./mimir.yaml:/etc/mimir/mimir.yaml:ro
      - mimir-data-2:/tmp/mimir-data
    networks:
      - mimir-net
    restart: unless-stopped

  mimir-3:
    image: grafana/mimir:${GRAFANA_MIMIR_VERSION:-2.13.0}
    hostname: mimir-3
    command:
      - -config.file=/etc/mimir/mimir.yaml
    volumes:
      - ./mimir.yaml:/etc/mimir/mimir.yaml:ro
      - mimir-data-3:/tmp/mimir-data
    networks:
      - mimir-net
    restart: unless-stopped

  # -------------------------
  # Grafana
  # -------------------------
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.0.2}
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - mimir-1
      - mimir-2
      - mimir-3
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<'EOF' > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Mimir
          type: prometheus
          access: proxy
          orgId: 1
          url: http://mimir-1:9009/prometheus
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        EOF
        /run.sh
    restart: unless-stopped

  # -------------------------
  # Alloy
  # -------------------------
  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.10.0}
    privileged: true
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    restart: unless-stopped

# -------------------------
# Volumes and Networks
# -------------------------
volumes:
  mimir-data-1:
  mimir-data-2:
  mimir-data-3:

networks:
  mimir-net:
